version: '3.9'
networks:
  notebook-network:
    driver: bridge
services:
  postgres:
    container_name: notebook-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: notebook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - notebook-postgres-data:/var/lib/postgresql/data
    networks:
      - notebook-network
  pgadmin4:
    container_name: notebook-pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@a48zomro.ml
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - notebook-pgadmin-data:/var/lib/pgadmin
    networks:
      - notebook-network

  notebook.api:
    container_name: notebook.api
    image: notebook.api
    build:
      context: .
      dockerfile: NoteBook.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:8080"
      - "5001:8081"
    networks:
      - notebook-network

volumes:
  notebook-postgres-data:
  notebook-pgadmin-data:
